
server:
  port: 8082
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: SOCIALPROJECT
    password: SOCIALPROJECT 
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
